### ISSUE TITLE
Singularity restart borks builds

### ISSUE THREAD

**Issue by rosibaj** [cancogen-virus-seq/singularity#27]
- archive was building and the service restarted
- archive did not complete building bc of restart
- - there is no build resume on build. 
- it looks to singularity based on the `build status`, `updated_date`, and `sample` that the archive was already in progress of building. 

## expected outcome
- Endpoint to remove in progress builds with authorization.

**Comment by leoraba** [comment]
2 new endpoints where added and are available since Singularity v0.6.0
It accepts an array of hash Ids to cancel, or an empty array to cancel the last building.
The buildings cancelled are tagged as `cancelled` in the database, and a Slack notification will be sent with the summary.

- PUT /build-archive/cancel

  - cancels the last building process started in the last 4hours. Body input:
  `{
      "items": []
  }`

  - cancels the building process(es) with the HashId passed in the body as array if it was started in the last 4 hours. e.g.
`{
    "items": ["1234567890"]
}`


- PUT /build-archive/force-cancel

  - cancels the last building process. Body input:
  `{
      "items": []
  }`

  - cancels the building process(es) with the HashId passed in the body as array. e.g.
`{
    "items": ["1234567890"]
}`
